version: "3.9"

services:
  db:
    image: chloem18/herstory-db:latest  # Utilisation de l'image personnalisée
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=HerStoryDatabase1507!
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql  # Volume pour persister les données SQL Server
    networks:
      - herstory_network

  backend:
    image: chloem18/herstory-backend:latest
    container_name: herstory-backend
    environment:
      - DB_CONNECTION_STRING=Server=sqlserver;Database=HerStory;User Id=sa;Password=HerStoryDatabase1507!;Encrypt=False;
      - JWT_SECRET=HerStorySecretKeyForJWTHoppefullyLongEnough
    ports:
      - "5103:5103"
    networks:
      - herstory_network
    depends_on:
      - db

  frontend:
    image: chloem18/herstory-frontend:latest
    container_name: herstory-frontend
    ports:
      - "4200:4200"
    networks:
      - herstory_network

volumes:
  db-data:  # Volume pour les données SQL Server

networks:
  herstory_network:
    driver: bridge
