name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./HerStory.Server   # Dossier contenant le Dockerfile du backend
          file: ./HerStory.Server/Dockerfile
          push: true
          tags: chloem18/herstory-backend:latest

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./herstory.client  # Dossier contenant le Dockerfile du frontend
          file: ./herstory.client/Dockerfile
          push: true
          tags: chloem18/herstory-frontend:latest

      - name: Build and push Database image
        uses: docker/build-push-action@v5
        with:
          context: ./scripts  # Dossier contenant le Dockerfile de la base de données
          file: ./scripts/Dockerfile
          push: true
          tags: chloem18/herstory-db:latest
